### ISSUE TITLE
Plugin can't install collections

### ISSUE THREAD

**Issue by syntaxaire** [QGIS-Contribution/QGIS-ResourceSharing#135] opened 2020-05-27 18:21 UTC
Steps to reproduce:
1. Install the latest version of the plugin (0.15.0) on the latest version of QGIS (3.12.3)
2. Open the plugin
3. Choose any item in the "All collections" list and click the Install button
4. Click the "Installed collections" list, it will be blank. 

Example:
![image](https://user-images.githubusercontent.com/2661404/83057444-e6394080-a024-11ea-9850-9b3fa872a93b.png)
![image](https://user-images.githubusercontent.com/2661404/83057483-f2bd9900-a024-11ea-9998-93db43f2613c.png)

![image](https://user-images.githubusercontent.com/2661404/83057518-02d57880-a025-11ea-90a4-ce44159951b4.png)

**Comment by havatv** [comment] 2020-05-27 20:28
Thank you for reporting, @syntaxaire!

I can't reproduce this on Windows 10 with QGIS 3.12.1 and version 0.15 of the plugin:

<img width="426" alt="resource_sharing_add" src="https://user-images.githubusercontent.com/1598812/83068251-5917db00-a068-11ea-8430-771ae5003858.png">

And the resource is installed:

<img width="427" alt="resource_sharing_installed" src="https://user-images.githubusercontent.com/1598812/83068458-adbb5600-a068-11ea-9601-74289ca7b109.png">

Are there any error messages in the *Log messages* panel?

Can you access (and clone) the github repository:
https://github.com/alinager/qgis-styles.git

**Comment by syntaxaire** [comment] 2020-05-27 20:56
Hi @havatv, I restarted QGIS and tried again, it still fails, but the following message appears in the log:
```2020-05-27T16:51:57     WARNING    Traceback (most recent call last):
              File "C:/Users/Jeff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\collection_manager.py", line 62, in run
              self._collection_manager.install(self._collection_id)
              File "C:/Users/Jeff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\collection_manager.py", line 209, in install
              resource_handler_instance.install()
              File "C:/Users/Jeff/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\resource_handler\svg_handler.py", line 67, in install
              search_paths.append(str(local_collection_path()))
             AttributeError: 'str' object has no attribute 'append'
             ```

**Comment by syntaxaire** [comment] 2020-05-27 21:02
I was able to install a collection that doesn't have any SVG components, the "Distance Measurement Styles". It shows up properly after installation.
![image](https://user-images.githubusercontent.com/2661404/83071827-b9dcee80-a03b-11ea-826c-42b6f12c2f05.png)
It does seem to be a bug with the SVG handler.

**Comment by havatv** [comment] 2020-05-27 21:13
Thanks a lot! I think I have found the cause of the issue.  Will try to fix.

**Comment by havatv** [comment] 2020-05-27 22:18
Current master contains a fix that I hope will solve this problem.
The issue arises if the QGIS `searchPathsForSVG` settings contains only one entry. In that case, the path is returned as a string by QgsSettings.value(), while the plugin was expecting a list. The fix is to make sure that if a string is returned from the settings, it will be turned into a (single entry) list.

@syntaxaire, could you try current master? If it works, we will close this issue and release version 0.15.1 with this fix.
1. download: https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/master.zip
2. unzip in your plugin directory
3. remove the directory that contains your current Resource Sharing plugin
4. (re)start QGIS
5. enable the plugin in the plugin manager
6. restart QGIS
7. run the plugin

Thanks again for your help!

**Comment by syntaxaire** [comment] 2020-05-28 02:48
Hi, the latest version of the plugin on GitHub fixes the issue.

**Comment by havatv** [comment] 2020-05-28 07:37
> Hi, the latest version of the plugin on GitHub fixes the issue.

Thanks for checking, @syntaxaire!
Then it should be safe to close this issue.

**Closed by havatv** 2020-05-28 07:37 UTC

**Comment by havatv** [comment] 2020-05-28 07:53
Version 0.15.1 (with the fix) is now on plugins.qgis.org. Thanks again, @syntaxaire!
