### ISSUE TITLE
Move the downloaded folder in the user profile

### ISSUE THREAD

**Issue by ghtmtt** [QGIS-Contribution/QGIS-ResourceSharing#109] opened 2020-04-17 15:48 UTC
In Linux (don't know in Windows or OSX) the first resource is downloaded a folder `$HOME/QGIS/Resource Sharing` is created. Isn't better to place it in the profile folder?

**Comment by havatv** [comment] 2020-04-17 20:36
Thanks for reporting!

I can not reproduce this with a fresh install of QGIS on Ubuntu 20.04. After adding the "Red Cross Emblems" collection, the `<QGIS Home>/resource_sharing/collections` directory was created, and contained the collection. `$HOME/QGIS` was not created.

The reason why you experience this could be that you have installed collections using an "old" version of the plugin (pre 0.10.0). See explanation below.

The default local file system location for collections was changed from `$HOME/QGIS/Resource Sharing` to `<QGIS Home>/resource_sharing/collections`. The location can be changed in settings (see http://qgis-contribution.github.io/QGIS-ResourceSharing/user/plugin-configuration.html) - **localCollectionDir** under *[ResourceSharing]*.
To avoid problems when upgrading the plugin, **localCollectionDir** was set to `$HOME/QGIS/Resource Sharing`if that directory contained collections.

**Comment by ghtmtt** [comment] 2020-04-18 10:40
mmm I'm using the 0.13 version just fresh installed. And this is the behavior on a Debian machine:

* in `/home/matteo` no QGIS folder is there (manually checked)
* plugin installed and downloaded the Red Cross svg as you did
* now I have `/home/matteo/QGIS/Resource Sharing/42e9bde23ea742ccb13d7265343394c54cc83a69` with the symbology
* I've also this folder: `/home/matteo/.local/share/QGIS/QGIS3/profiles/mat/resource_sharing`

So the folder in my home dir is created by the plugin when downloading some collection

**Comment by havatv** [comment] 2020-04-18 11:35
> mmm I'm using the 0.13 version just fresh installed. And this is the behavior on a Debian machine:
> 
>     * in `/home/matteo` no QGIS folder is there (manually checked)
> 
>     * plugin installed and downloaded the Red Cross svg as you did
> 
>     * now I have `/home/matteo/QGIS/Resource Sharing/42e9bde23ea742ccb13d7265343394c54cc83a69` with the symbology
> 
>     * I've also this folder: `/home/matteo/.local/share/QGIS/QGIS3/profiles/mat/resource_sharing`
> 
> 
> So the folder in my home dir is created by the plugin when downloading some collection

Have you checked if `localCollectionDir` is defined in QGIS settings?
(can be checked in settings-> Advanced-> ResourceSharing or in the QGIS3.ini file - ~/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini on Ubuntu)

**Comment by ghtmtt** [comment] 2020-04-20 07:26
Confirmed. In advanced settings QGIS Resource is pointing to my `home` folder. I read the other issue but I'm a bit confused. So the *problem* of the home folder is only if the plugin is upgraded from older versions? Else the standard location is the profile folder?

Thanks!

**Comment by havatv** [comment] 2020-04-20 07:51
> Confirmed. In advanced settings QGIS Resource is pointing to my `home` folder. I read the other issue but I'm a bit confused. So the _problem_ of the home folder is only if the plugin is upgraded from older versions? Else the standard location is the profile folder?

That should be the behaviour. The procedure is as follows (`utilities.py`):

1. The plugin first checks if ***localCollectionDir*** is present in settings. If it is, the location is taken from there.
2. If ***localCollectionDir*** is not in settings, the plugin checks if the `~/QGIS/Resource Sharing`  directory exists (indicating that an earlier version of the plugin has been used to download collections). If it does, that directory is used and stored in the ***localCollectionDir*** setting.
3. If the directory does not exist, `<QGIS_user_dir>/resource_sharing/collections` is used (and stored in the ***localCollectionDir*** setting).

Do you think this behaviour is logical and acceptable, @ghtmtt ?

**Comment by ghtmtt** [comment] 2020-04-20 08:20
clear explanation, thanks!.

mmmm.. I will switch `2` with `3`. As a User I'm expecting that all the behavior of (all) the plugin is stored by default in the profile folder and not in the home one. E.g. if I've created a nice profile with some plugin and less buttons to share with colleagues, I'm expecting that also their QGIS is running with Resource Sharing and the resources downloaded.

**Comment by havatv** [comment] 2020-04-20 08:49
In my opinion, the current procedure is to be preferred.

* New users of the plugin will have their collections stored under the "profile" folder.
* Those that have used earlier versions of the plugin will not have to (re)install the collections they are using, and will not experience any problems with SVG paths, etc.
* Those that have strong opinions when it comes to using the home folder versus profile folder can update the ***localCollectionDir*** setting, and move or reinstall their collections.

I have updated the documentation to make the behaviour more clear.
Thank you for the feedback, @ghtmtt. Since the behaviour you experience is reasonable and documented, I will close this issue now. If you have strong opinions on this, I suggest that you create an enhancement issue where we can invite more people into the discussion.

**Closed by havatv** 2020-04-20 08:49 UTC
Labels: Documentation
